services:
  - type: web
    name: sagartransport
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_ACCESS_KEY_SECRET
        sync: false
      - key: CLOUDFLARE_R2_BUCKET_NAME
        sync: false
      - key: CLOUDFLARE_R2_PUBLIC_URL
        sync: false
      - key: DRIVE_ROOT_FOLDER_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
